import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../l10n/generated/app_localizations.dart';
import 'package:moroka/core/constants/app_colors.dart';
import 'package:moroka/core/constants/app_text_styles.dart';
import 'package:moroka/core/utils/haptic_utils.dart';
import 'package:moroka/presentation/widgets/common/animated_gradient_background.dart';
import 'package:moroka/presentation/widgets/common/glass_morphism_container.dart';
import 'package:moroka/presentation/widgets/common/custom_loading_indicator.dart';

class TermsScreen extends StatefulWidget {
  final String type;
  
  const TermsScreen({super.key, this.type = 'terms'});

  @override
  State<TermsScreen> createState() => _TermsScreenState();
}

class _TermsScreenState extends State<TermsScreen> {
  final ScrollController _scrollController = ScrollController();
  bool _isLoading = true;
  
  @override
  void initState() {
    super.initState();
    // Simulate loading terms content
    Future.delayed(const Duration(milliseconds: 500), () {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    });
  }
  
  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }
  
  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final isPrivacyPolicy = widget.type == 'privacy';
    
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios),
          onPressed: () {
            HapticUtils.lightImpact();
            context.pop();
          },
        ),
        title: Text(
          isPrivacyPolicy ? l10n.privacyPolicy : l10n.termsOfService,
          style: AppTextStyles.heading2,
        ),
        centerTitle: true,
      ),
      body: Stack(
        children: [
          const AnimatedGradientBackground(child: SizedBox.expand()),
          SafeArea(
            child: _isLoading
                ? const Center(child: CustomLoadingIndicator())
                : Padding(
                    padding: const EdgeInsets.all(20),
                    child: GlassMorphismContainer(
                      padding: const EdgeInsets.all(24),
                      child: SingleChildScrollView(
                        controller: _scrollController,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            if (isPrivacyPolicy)
                              ..._buildPrivacyPolicyContent(l10n)
                            else
                              ..._buildTermsContent(l10n),
                          ],
                        ),
                      ),
                    ),
                  ),
          ),
        ],
      ),
    );
  }
  
  List<Widget> _buildTermsContent(AppLocalizations l10n) {
    return [
      Text(
        'Terms of Service',
        style: AppTextStyles.heading2.copyWith(color: AppColors.primary),
      ),
      const SizedBox(height: 24),
      Text(
        'Last updated: ${DateTime.now().year}',
        style: AppTextStyles.caption.copyWith(color: AppColors.textSecondary),
      ),
      const SizedBox(height: 24),
      _buildSection(
        '1. Acceptance of Terms',
        'By accessing and using Moroka Tarot ("the App"), you accept and agree to be bound by the terms and provision of this agreement.',
      ),
      _buildSection(
        '2. Use License',
        'Permission is granted to temporarily download one copy of the App for personal, non-commercial transitory viewing only.',
      ),
      _buildSection(
        '3. Service Description',
        'Moroka Tarot provides digital tarot card reading services powered by AI. The readings are for entertainment and personal reflection purposes only.',
      ),
      _buildSection(
        '4. User Accounts',
        'You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.',
      ),
      _buildSection(
        '5. Content',
        'All tarot interpretations and guidance provided by the App are generated by AI and should not be considered as professional advice.',
      ),
      _buildSection(
        '6. Privacy',
        'Your use of our App is also governed by our Privacy Policy. Please review our Privacy Policy, which also governs the Site and informs users of our data collection practices.',
      ),
      _buildSection(
        '7. Prohibited Uses',
        'You may not use the App:\n• For any unlawful purpose\n• To solicit others to perform unlawful acts\n• To violate any international, federal, provincial, or state regulations, rules, laws, or local ordinances\n• To infringe upon or violate our intellectual property rights',
      ),
      _buildSection(
        '8. Termination',
        'We may terminate or suspend your account and bar access to the App immediately, without prior notice or liability, under our sole discretion.',
      ),
      _buildSection(
        '9. Changes to Terms',
        'We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days notice prior to any new terms taking effect.',
      ),
      _buildSection(
        '10. Contact Information',
        'If you have any questions about these Terms, please contact us through the App.',
      ),
    ];
  }
  
  List<Widget> _buildPrivacyPolicyContent(AppLocalizations l10n) {
    return [
      Text(
        'Privacy Policy',
        style: AppTextStyles.heading2.copyWith(color: AppColors.primary),
      ),
      const SizedBox(height: 24),
      Text(
        'Last updated: ${DateTime.now().year}',
        style: AppTextStyles.caption.copyWith(color: AppColors.textSecondary),
      ),
      const SizedBox(height: 24),
      _buildSection(
        '1. Information We Collect',
        'We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support.',
      ),
      _buildSection(
        '2. Personal Information',
        '• Email address\n• Display name\n• Profile information\n• Reading history and preferences',
      ),
      _buildSection(
        '3. Usage Data',
        'We automatically collect certain information about your device and how you interact with our App:\n• Device information\n• Log data\n• Usage patterns\n• Performance data',
      ),
      _buildSection(
        '4. How We Use Your Information',
        '• To provide and maintain our services\n• To personalize your experience\n• To improve our App\n• To communicate with you\n• To ensure security and prevent fraud',
      ),
      _buildSection(
        '5. Data Storage',
        'Your data is securely stored using Firebase services. We implement appropriate technical and organizational measures to protect your personal information.',
      ),
      _buildSection(
        '6. Data Sharing',
        'We do not sell, trade, or rent your personal information to third parties. We may share your information only in the following circumstances:\n• With your consent\n• To comply with legal obligations\n• To protect our rights and safety',
      ),
      _buildSection(
        '7. Your Rights',
        'You have the right to:\n• Access your personal data\n• Correct inaccurate data\n• Request deletion of your data\n• Export your data\n• Opt-out of certain communications',
      ),
      _buildSection(
        '8. Data Retention',
        'We retain your personal information for as long as necessary to provide our services and fulfill the purposes described in this policy.',
      ),
      _buildSection(
        '9. Children\'s Privacy',
        'Our App is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13.',
      ),
      _buildSection(
        '10. Changes to This Policy',
        'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
      ),
      _buildSection(
        '11. Contact Us',
        'If you have any questions about this Privacy Policy, please contact us through the App.',
      ),
    ];
  }
  
  Widget _buildSection(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: AppTextStyles.heading3.copyWith(
              color: AppColors.primary,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: AppTextStyles.body1.copyWith(
              color: AppColors.textPrimary,
              height: 1.6,
            ),
          ),
        ],
      ),
    );
  }
}