// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8lp0PbGkrsqhQTDEoRGVDN9zb7kqHLp8',
    appId: '1:692624774743:web:ae26a04c002357f7603512',
    messagingSenderId: '692624774743',
    projectId: 'moroka-32704',
    authDomain: 'moroka-32704.firebaseapp.com',
    storageBucket: 'moroka-32704.firebasestorage.app',
    measurementId: 'G-9JLRMQZX9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzgRYBfD8UOUGpefdYuGxmGUctG_O6So',
    appId: '1:692624774743:android:4e1e47d1ffb7ee63603512',
    messagingSenderId: '692624774743',
    projectId: 'moroka-32704',
    storageBucket: 'moroka-32704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLK0hlYOMmEc_doBm0gI_T6XaKQg_aLgo',
    appId: '1:692624774743:ios:7e05f96741e7912d603512',
    messagingSenderId: '692624774743',
    projectId: 'moroka-32704',
    storageBucket: 'moroka-32704.firebasestorage.app',
    androidClientId: '692624774743-k93fc9r70lr0jitpl540in671vnoft1f.apps.googleusercontent.com',
    iosClientId: '692624774743-leo641np8qqbvl6tpls6hti4k0ir4k3i.apps.googleusercontent.com',
    iosBundleId: 'com.chlee.moroka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLK0hlYOMmEc_doBm0gI_T6XaKQg_aLgo',
    appId: '1:692624774743:ios:7e05f96741e7912d603512',
    messagingSenderId: '692624774743',
    projectId: 'moroka-32704',
    storageBucket: 'moroka-32704.firebasestorage.app',
    androidClientId: '692624774743-k93fc9r70lr0jitpl540in671vnoft1f.apps.googleusercontent.com',
    iosClientId: '692624774743-leo641np8qqbvl6tpls6hti4k0ir4k3i.apps.googleusercontent.com',
    iosBundleId: 'com.chlee.moroka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8lp0PbGkrsqhQTDEoRGVDN9zb7kqHLp8',
    appId: '1:692624774743:web:5dcd43698037cfbb603512',
    messagingSenderId: '692624774743',
    projectId: 'moroka-32704',
    authDomain: 'moroka-32704.firebaseapp.com',
    storageBucket: 'moroka-32704.firebasestorage.app',
    measurementId: 'G-XCSLBKYHPJ',
  );
}
